.class public final LzU/g;
.super LI30/k;
.source "SourceFile"


# static fields
.field public static final f:LB30/z;

.field public static final g:LI30/g;

.field public static final h:LI30/i;

.field public static final i:LI30/h;


# instance fields
.field public a:Ljava/lang/CharSequence;

.field public b:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List<",
            "Ljava/lang/CharSequence;",
            ">;"
        }
    .end annotation
.end field

.field public c:Ljava/lang/Boolean;

.field public d:Ljava/lang/Integer;

.field public e:Ljava/lang/CharSequence;


# direct methods
.method static constructor <clinit>()V
    .locals 3

    .line 1
    const-string v0, "{\"type\":\"record\",\"name\":\"AdRequestConfig\",\"namespace\":\"com.truecaller.tracking.events\",\"fields\":[{\"name\":\"gamAdRequestId\",\"type\":[\"null\",\"string\"],\"doc\":\"This field captures the unique request ID generated by Google Ad Manager for the ad request.\",\"default\":null},{\"name\":\"cachedAdsSkiped\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}],\"doc\":\"This field indicates whether the ad request bypassed existing cached ads.\",\"default\":null},{\"name\":\"isCached\",\"type\":[\"null\",\"boolean\"],\"doc\":\"This field specifies whether the ad request is configured to cache the ad for future use.\",\"default\":null},{\"name\":\"cacheConfigVersion\",\"type\":[\"null\",\"int\"],\"doc\":\"This field provides the version of the cache configuration used internally for ad requests.\",\"default\":null},{\"name\":\"messageId\",\"type\":[\"null\",\"string\"],\"doc\":\"Id generated by insights for message id\",\"default\":null}]}"

    .line 2
    .line 3
    invoke-static {v0}, LJh/qux;->a(Ljava/lang/String;)LB30/z;

    .line 4
    .line 5
    .line 6
    move-result-object v0

    .line 7
    sput-object v0, LzU/g;->f:LB30/z;

    .line 8
    .line 9
    new-instance v1, LI30/g;

    .line 10
    .line 11
    invoke-direct {v1}, LI30/g;-><init>()V

    .line 12
    .line 13
    .line 14
    sput-object v1, LzU/g;->g:LI30/g;

    .line 15
    .line 16
    new-instance v2, LG30/a;

    .line 17
    .line 18
    invoke-direct {v2, v1, v0}, LG30/a;-><init>(LI30/g;LB30/z;)V

    .line 19
    .line 20
    .line 21
    new-instance v2, LG30/qux;

    .line 22
    .line 23
    invoke-direct {v2, v1, v0}, LG30/qux;-><init>(LI30/g;LB30/z;)V

    .line 24
    .line 25
    .line 26
    new-instance v2, LI30/i;

    .line 27
    .line 28
    invoke-direct {v2, v0, v1}, LD30/r;-><init>(LB30/z;LD30/f;)V

    .line 29
    .line 30
    .line 31
    sput-object v2, LzU/g;->h:LI30/i;

    .line 32
    .line 33
    new-instance v2, LI30/h;

    .line 34
    .line 35
    invoke-direct {v2, v0, v0, v1}, LI30/h;-><init>(LB30/z;LB30/z;LI30/g;)V

    .line 36
    .line 37
    .line 38
    sput-object v2, LzU/g;->i:LI30/h;

    .line 39
    .line 40
    return-void
    .line 41
    .line 42
    .line 43
    .line 44
    .line 45
    .line 46
    .line 47
    .line 48
    .line 49
    .line 50
    .line 51
    .line 52
    .line 53
    .line 54
    .line 55
    .line 56
    .line 57
    .line 58
    .line 59
    .line 60
    .line 61
    .line 62
    .line 63
    .line 64
    .line 65
    .line 66
    .line 67
    .line 68
    .line 69
    .line 70
    .line 71
    .line 72
    .line 73
    .line 74
    .line 75
    .line 76
    .line 77
    .line 78
    .line 79
    .line 80
.end method

.method public constructor <init>()V
    .locals 0

    .line 1
    invoke-direct {p0}, LI30/k;-><init>()V

    return-void
.end method

.method public constructor <init>(Ljava/lang/CharSequence;Ljava/util/List;Ljava/lang/Boolean;Ljava/lang/Integer;Ljava/lang/String;)V
    .locals 0

    .line 2
    invoke-direct {p0}, LI30/k;-><init>()V

    .line 3
    iput-object p1, p0, LzU/g;->a:Ljava/lang/CharSequence;

    .line 4
    iput-object p2, p0, LzU/g;->b:Ljava/util/List;

    .line 5
    iput-object p3, p0, LzU/g;->c:Ljava/lang/Boolean;

    .line 6
    iput-object p4, p0, LzU/g;->d:Ljava/lang/Integer;

    .line 7
    iput-object p5, p0, LzU/g;->e:Ljava/lang/CharSequence;

    return-void
.end method


# virtual methods
.method public final a(ILjava/lang/Object;)V
    .locals 1

    .line 1
    if-eqz p1, :cond_4

    .line 2
    .line 3
    const/4 v0, 0x1

    .line 4
    if-eq p1, v0, :cond_3

    .line 5
    .line 6
    const/4 v0, 0x2

    .line 7
    if-eq p1, v0, :cond_2

    .line 8
    .line 9
    const/4 v0, 0x3

    .line 10
    if-eq p1, v0, :cond_1

    .line 11
    .line 12
    const/4 v0, 0x4

    .line 13
    if-ne p1, v0, :cond_0

    .line 14
    .line 15
    check-cast p2, Ljava/lang/CharSequence;

    .line 16
    .line 17
    iput-object p2, p0, LzU/g;->e:Ljava/lang/CharSequence;

    .line 18
    .line 19
    return-void

    .line 20
    :cond_0
    new-instance p2, Ljava/lang/IndexOutOfBoundsException;

    .line 21
    .line 22
    const-string v0, "Invalid index: "

    .line 23
    .line 24
    invoke-static {p1, v0}, Ld;->a(ILjava/lang/String;)Ljava/lang/String;

    .line 25
    .line 26
    .line 27
    move-result-object p1

    .line 28
    invoke-direct {p2, p1}, Ljava/lang/IndexOutOfBoundsException;-><init>(Ljava/lang/String;)V

    .line 29
    .line 30
    .line 31
    throw p2

    .line 32
    :cond_1
    check-cast p2, Ljava/lang/Integer;

    .line 33
    .line 34
    iput-object p2, p0, LzU/g;->d:Ljava/lang/Integer;

    .line 35
    .line 36
    return-void

    .line 37
    :cond_2
    check-cast p2, Ljava/lang/Boolean;

    .line 38
    .line 39
    iput-object p2, p0, LzU/g;->c:Ljava/lang/Boolean;

    .line 40
    .line 41
    return-void

    .line 42
    :cond_3
    check-cast p2, Ljava/util/List;

    .line 43
    .line 44
    iput-object p2, p0, LzU/g;->b:Ljava/util/List;

    .line 45
    .line 46
    return-void

    .line 47
    :cond_4
    check-cast p2, Ljava/lang/CharSequence;

    .line 48
    .line 49
    iput-object p2, p0, LzU/g;->a:Ljava/lang/CharSequence;

    .line 50
    .line 51
    return-void
    .line 52
    .line 53
    .line 54
    .line 55
    .line 56
    .line 57
    .line 58
    .line 59
    .line 60
    .line 61
    .line 62
    .line 63
    .line 64
    .line 65
    .line 66
    .line 67
    .line 68
    .line 69
    .line 70
    .line 71
    .line 72
    .line 73
    .line 74
    .line 75
    .line 76
    .line 77
    .line 78
    .line 79
    .line 80
    .line 81
    .line 82
    .line 83
    .line 84
    .line 85
    .line 86
    .line 87
    .line 88
    .line 89
    .line 90
    .line 91
    .line 92
    .line 93
    .line 94
    .line 95
    .line 96
    .line 97
    .line 98
    .line 99
    .line 100
    .line 101
    .line 102
    .line 103
    .line 104
    .line 105
    .line 106
    .line 107
    .line 108
    .line 109
    .line 110
    .line 111
    .line 112
    .line 113
    .line 114
    .line 115
    .line 116
    .line 117
    .line 118
    .line 119
    .line 120
    .line 121
    .line 122
    .line 123
    .line 124
    .line 125
    .line 126
    .line 127
    .line 128
    .line 129
    .line 130
    .line 131
    .line 132
    .line 133
    .line 134
    .line 135
    .line 136
    .line 137
    .line 138
    .line 139
    .line 140
    .line 141
    .line 142
    .line 143
    .line 144
    .line 145
    .line 146
    .line 147
    .line 148
    .line 149
    .line 150
    .line 151
    .line 152
    .line 153
    .line 154
    .line 155
    .line 156
    .line 157
    .line 158
    .line 159
    .line 160
    .line 161
    .line 162
    .line 163
    .line 164
    .line 165
    .line 166
    .line 167
    .line 168
    .line 169
    .line 170
    .line 171
    .line 172
    .line 173
    .line 174
    .line 175
    .line 176
    .line 177
    .line 178
    .line 179
    .line 180
    .line 181
    .line 182
    .line 183
    .line 184
    .line 185
    .line 186
    .line 187
    .line 188
    .line 189
    .line 190
    .line 191
    .line 192
    .line 193
    .line 194
    .line 195
    .line 196
    .line 197
    .line 198
    .line 199
    .line 200
    .line 201
    .line 202
    .line 203
    .line 204
    .line 205
    .line 206
    .line 207
    .line 208
    .line 209
    .line 210
    .line 211
    .line 212
    .line 213
    .line 214
    .line 215
.end method

.method public final g(LE30/d0;)V
    .locals 19
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    .line 1
    move-object/from16 v0, p0

    .line 2
    .line 3
    move-object/from16 v1, p1

    .line 4
    .line 5
    invoke-virtual {v1}, LE30/d0;->x()[LB30/z$c;

    .line 6
    .line 7
    .line 8
    move-result-object v8

    .line 9
    const-wide/16 v6, 0x1

    .line 10
    .line 11
    const-string v9, "cachedAdsSkiped"

    .line 12
    .line 13
    sget-object v10, LzU/g;->f:LB30/z;

    .line 14
    .line 15
    const-wide/16 v11, 0x0

    .line 16
    .line 17
    const/4 v13, 0x1

    .line 18
    const/4 v14, 0x0

    .line 19
    if-nez v8, :cond_d

    .line 20
    .line 21
    invoke-virtual {v1}, LE30/d0;->j()I

    .line 22
    .line 23
    .line 24
    move-result v2

    .line 25
    if-eq v2, v13, :cond_0

    .line 26
    .line 27
    invoke-virtual {v1}, LE30/e0;->n()V

    .line 28
    .line 29
    .line 30
    iput-object v14, v0, LzU/g;->a:Ljava/lang/CharSequence;

    .line 31
    .line 32
    goto :goto_1

    .line 33
    :cond_0
    iget-object v2, v0, LzU/g;->a:Ljava/lang/CharSequence;

    .line 34
    .line 35
    instance-of v3, v2, LJ30/F;

    .line 36
    .line 37
    if-eqz v3, :cond_1

    .line 38
    .line 39
    check-cast v2, LJ30/F;

    .line 40
    .line 41
    goto :goto_0

    .line 42
    :cond_1
    move-object v2, v14

    .line 43
    :goto_0
    invoke-virtual {v1, v2}, LE30/d0;->o(LJ30/F;)LJ30/F;

    .line 44
    .line 45
    .line 46
    move-result-object v2

    .line 47
    iput-object v2, v0, LzU/g;->a:Ljava/lang/CharSequence;

    .line 48
    .line 49
    :goto_1
    invoke-virtual {v1}, LE30/d0;->j()I

    .line 50
    .line 51
    .line 52
    move-result v2

    .line 53
    if-eq v2, v13, :cond_2

    .line 54
    .line 55
    invoke-virtual {v1}, LE30/e0;->n()V

    .line 56
    .line 57
    .line 58
    iput-object v14, v0, LzU/g;->b:Ljava/util/List;

    .line 59
    .line 60
    goto/16 :goto_8

    .line 61
    .line 62
    :cond_2
    invoke-virtual {v1}, LE30/e0;->c()J

    .line 63
    .line 64
    .line 65
    move-result-wide v2

    .line 66
    iget-object v4, v0, LzU/g;->b:Ljava/util/List;

    .line 67
    .line 68
    if-nez v4, :cond_3

    .line 69
    .line 70
    new-instance v4, LD30/f$baz;

    .line 71
    .line 72
    long-to-int v5, v2

    .line 73
    invoke-virtual {v10, v9}, LB30/z;->v(Ljava/lang/String;)LB30/z$c;

    .line 74
    .line 75
    .line 76
    move-result-object v8

    .line 77
    iget-object v8, v8, LB30/z$c;->f:LB30/z;

    .line 78
    .line 79
    invoke-virtual {v8}, LB30/z;->C()Ljava/util/List;

    .line 80
    .line 81
    .line 82
    move-result-object v8

    .line 83
    invoke-interface {v8, v13}, Ljava/util/List;->get(I)Ljava/lang/Object;

    .line 84
    .line 85
    .line 86
    move-result-object v8

    .line 87
    check-cast v8, LB30/z;

    .line 88
    .line 89
    invoke-direct {v4, v5, v8}, LD30/f$baz;-><init>(ILB30/z;)V

    .line 90
    .line 91
    .line 92
    iput-object v4, v0, LzU/g;->b:Ljava/util/List;

    .line 93
    .line 94
    goto :goto_2

    .line 95
    :cond_3
    invoke-interface {v4}, Ljava/util/List;->clear()V

    .line 96
    .line 97
    .line 98
    :goto_2
    instance-of v5, v4, LD30/f$baz;

    .line 99
    .line 100
    if-eqz v5, :cond_4

    .line 101
    .line 102
    move-object v5, v4

    .line 103
    check-cast v5, LD30/f$baz;

    .line 104
    .line 105
    move-object v8, v5

    .line 106
    goto :goto_3

    .line 107
    :cond_4
    move-object v8, v14

    .line 108
    :goto_3
    cmp-long v5, v11, v2

    .line 109
    .line 110
    if-gez v5, :cond_8

    .line 111
    .line 112
    :goto_4
    cmp-long v5, v2, v11

    .line 113
    .line 114
    if-eqz v5, :cond_7

    .line 115
    .line 116
    if-eqz v8, :cond_5

    .line 117
    .line 118
    invoke-virtual {v8}, LD30/f$baz;->peek()Ljava/lang/Object;

    .line 119
    .line 120
    .line 121
    move-result-object v5

    .line 122
    check-cast v5, Ljava/lang/CharSequence;

    .line 123
    .line 124
    goto :goto_5

    .line 125
    :cond_5
    move-object v5, v14

    .line 126
    :goto_5
    instance-of v9, v5, LJ30/F;

    .line 127
    .line 128
    if-eqz v9, :cond_6

    .line 129
    .line 130
    check-cast v5, LJ30/F;

    .line 131
    .line 132
    move-wide/from16 v17, v2

    .line 133
    .line 134
    move-object v2, v5

    .line 135
    :goto_6
    move-object v3, v4

    .line 136
    move-wide/from16 v4, v17

    .line 137
    .line 138
    goto :goto_7

    .line 139
    :cond_6
    move-wide/from16 v17, v2

    .line 140
    .line 141
    move-object v2, v14

    .line 142
    goto :goto_6

    .line 143
    :goto_7
    invoke-static/range {v1 .. v7}, LzU/f;->a(LE30/d0;LJ30/F;Ljava/util/List;JJ)J

    .line 144
    .line 145
    .line 146
    move-result-wide v4

    .line 147
    move-wide/from16 v17, v4

    .line 148
    .line 149
    move-object v4, v3

    .line 150
    move-wide/from16 v2, v17

    .line 151
    .line 152
    goto :goto_4

    .line 153
    :cond_7
    move-object v3, v4

    .line 154
    invoke-virtual {v1}, LE30/e0;->a()J

    .line 155
    .line 156
    .line 157
    move-result-wide v4

    .line 158
    move-wide/from16 v17, v4

    .line 159
    .line 160
    move-object v4, v3

    .line 161
    move-wide/from16 v2, v17

    .line 162
    .line 163
    goto :goto_3

    .line 164
    :cond_8
    :goto_8
    invoke-virtual {v1}, LE30/d0;->j()I

    .line 165
    .line 166
    .line 167
    move-result v2

    .line 168
    if-eq v2, v13, :cond_9

    .line 169
    .line 170
    invoke-virtual {v1}, LE30/e0;->n()V

    .line 171
    .line 172
    .line 173
    iput-object v14, v0, LzU/g;->c:Ljava/lang/Boolean;

    .line 174
    .line 175
    goto :goto_9

    .line 176
    :cond_9
    invoke-virtual {v1}, LE30/e0;->d()Z

    .line 177
    .line 178
    .line 179
    move-result v2

    .line 180
    invoke-static {v2}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 181
    .line 182
    .line 183
    move-result-object v2

    .line 184
    iput-object v2, v0, LzU/g;->c:Ljava/lang/Boolean;

    .line 185
    .line 186
    :goto_9
    invoke-virtual {v1}, LE30/d0;->j()I

    .line 187
    .line 188
    .line 189
    move-result v2

    .line 190
    if-eq v2, v13, :cond_a

    .line 191
    .line 192
    invoke-virtual {v1}, LE30/e0;->n()V

    .line 193
    .line 194
    .line 195
    iput-object v14, v0, LzU/g;->d:Ljava/lang/Integer;

    .line 196
    .line 197
    goto :goto_a

    .line 198
    :cond_a
    invoke-virtual {v1}, LE30/e0;->k()I

    .line 199
    .line 200
    .line 201
    move-result v2

    .line 202
    invoke-static {v2}, Ljava/lang/Integer;->valueOf(I)Ljava/lang/Integer;

    .line 203
    .line 204
    .line 205
    move-result-object v2

    .line 206
    iput-object v2, v0, LzU/g;->d:Ljava/lang/Integer;

    .line 207
    .line 208
    :goto_a
    invoke-virtual {v1}, LE30/d0;->j()I

    .line 209
    .line 210
    .line 211
    move-result v2

    .line 212
    if-eq v2, v13, :cond_b

    .line 213
    .line 214
    invoke-virtual {v1}, LE30/e0;->n()V

    .line 215
    .line 216
    .line 217
    iput-object v14, v0, LzU/g;->e:Ljava/lang/CharSequence;

    .line 218
    .line 219
    return-void

    .line 220
    :cond_b
    iget-object v2, v0, LzU/g;->e:Ljava/lang/CharSequence;

    .line 221
    .line 222
    instance-of v3, v2, LJ30/F;

    .line 223
    .line 224
    if-eqz v3, :cond_c

    .line 225
    .line 226
    move-object v14, v2

    .line 227
    check-cast v14, LJ30/F;

    .line 228
    .line 229
    :cond_c
    invoke-virtual {v1, v14}, LE30/d0;->o(LJ30/F;)LJ30/F;

    .line 230
    .line 231
    .line 232
    move-result-object v1

    .line 233
    iput-object v1, v0, LzU/g;->e:Ljava/lang/CharSequence;

    .line 234
    .line 235
    return-void

    .line 236
    :cond_d
    const/4 v2, 0x0

    .line 237
    move v15, v2

    .line 238
    :goto_b
    const/4 v2, 0x5

    .line 239
    if-ge v15, v2, :cond_20

    .line 240
    .line 241
    aget-object v2, v8, v15

    .line 242
    .line 243
    iget v2, v2, LB30/z$c;->e:I

    .line 244
    .line 245
    if-eqz v2, :cond_1d

    .line 246
    .line 247
    if-eq v2, v13, :cond_15

    .line 248
    .line 249
    const/4 v3, 0x2

    .line 250
    if-eq v2, v3, :cond_13

    .line 251
    .line 252
    const/4 v3, 0x3

    .line 253
    if-eq v2, v3, :cond_11

    .line 254
    .line 255
    const/4 v3, 0x4

    .line 256
    if-ne v2, v3, :cond_10

    .line 257
    .line 258
    invoke-virtual {v1}, LE30/d0;->j()I

    .line 259
    .line 260
    .line 261
    move-result v2

    .line 262
    if-eq v2, v13, :cond_e

    .line 263
    .line 264
    invoke-virtual {v1}, LE30/e0;->n()V

    .line 265
    .line 266
    .line 267
    iput-object v14, v0, LzU/g;->e:Ljava/lang/CharSequence;

    .line 268
    .line 269
    goto/16 :goto_14

    .line 270
    .line 271
    :cond_e
    iget-object v2, v0, LzU/g;->e:Ljava/lang/CharSequence;

    .line 272
    .line 273
    instance-of v3, v2, LJ30/F;

    .line 274
    .line 275
    if-eqz v3, :cond_f

    .line 276
    .line 277
    check-cast v2, LJ30/F;

    .line 278
    .line 279
    goto :goto_c

    .line 280
    :cond_f
    move-object v2, v14

    .line 281
    :goto_c
    invoke-virtual {v1, v2}, LE30/d0;->o(LJ30/F;)LJ30/F;

    .line 282
    .line 283
    .line 284
    move-result-object v2

    .line 285
    iput-object v2, v0, LzU/g;->e:Ljava/lang/CharSequence;

    .line 286
    .line 287
    goto/16 :goto_14

    .line 288
    .line 289
    :cond_10
    new-instance v1, Ljava/io/IOException;

    .line 290
    .line 291
    const-string v2, "Corrupt ResolvingDecoder."

    .line 292
    .line 293
    invoke-direct {v1, v2}, Ljava/io/IOException;-><init>(Ljava/lang/String;)V

    .line 294
    .line 295
    .line 296
    throw v1

    .line 297
    :cond_11
    invoke-virtual {v1}, LE30/d0;->j()I

    .line 298
    .line 299
    .line 300
    move-result v2

    .line 301
    if-eq v2, v13, :cond_12

    .line 302
    .line 303
    invoke-virtual {v1}, LE30/e0;->n()V

    .line 304
    .line 305
    .line 306
    iput-object v14, v0, LzU/g;->d:Ljava/lang/Integer;

    .line 307
    .line 308
    goto/16 :goto_14

    .line 309
    .line 310
    :cond_12
    invoke-virtual {v1}, LE30/e0;->k()I

    .line 311
    .line 312
    .line 313
    move-result v2

    .line 314
    invoke-static {v2}, Ljava/lang/Integer;->valueOf(I)Ljava/lang/Integer;

    .line 315
    .line 316
    .line 317
    move-result-object v2

    .line 318
    iput-object v2, v0, LzU/g;->d:Ljava/lang/Integer;

    .line 319
    .line 320
    goto/16 :goto_14

    .line 321
    .line 322
    :cond_13
    invoke-virtual {v1}, LE30/d0;->j()I

    .line 323
    .line 324
    .line 325
    move-result v2

    .line 326
    if-eq v2, v13, :cond_14

    .line 327
    .line 328
    invoke-virtual {v1}, LE30/e0;->n()V

    .line 329
    .line 330
    .line 331
    iput-object v14, v0, LzU/g;->c:Ljava/lang/Boolean;

    .line 332
    .line 333
    goto/16 :goto_14

    .line 334
    .line 335
    :cond_14
    invoke-virtual {v1}, LE30/e0;->d()Z

    .line 336
    .line 337
    .line 338
    move-result v2

    .line 339
    invoke-static {v2}, Ljava/lang/Boolean;->valueOf(Z)Ljava/lang/Boolean;

    .line 340
    .line 341
    .line 342
    move-result-object v2

    .line 343
    iput-object v2, v0, LzU/g;->c:Ljava/lang/Boolean;

    .line 344
    .line 345
    goto/16 :goto_14

    .line 346
    .line 347
    :cond_15
    invoke-virtual {v1}, LE30/d0;->j()I

    .line 348
    .line 349
    .line 350
    move-result v2

    .line 351
    if-eq v2, v13, :cond_16

    .line 352
    .line 353
    invoke-virtual {v1}, LE30/e0;->n()V

    .line 354
    .line 355
    .line 356
    iput-object v14, v0, LzU/g;->b:Ljava/util/List;

    .line 357
    .line 358
    goto/16 :goto_14

    .line 359
    .line 360
    :cond_16
    invoke-virtual {v1}, LE30/e0;->c()J

    .line 361
    .line 362
    .line 363
    move-result-wide v2

    .line 364
    iget-object v4, v0, LzU/g;->b:Ljava/util/List;

    .line 365
    .line 366
    if-nez v4, :cond_17

    .line 367
    .line 368
    new-instance v4, LD30/f$baz;

    .line 369
    .line 370
    long-to-int v5, v2

    .line 371
    invoke-virtual {v10, v9}, LB30/z;->v(Ljava/lang/String;)LB30/z$c;

    .line 372
    .line 373
    .line 374
    move-result-object v6

    .line 375
    iget-object v6, v6, LB30/z$c;->f:LB30/z;

    .line 376
    .line 377
    invoke-virtual {v6}, LB30/z;->C()Ljava/util/List;

    .line 378
    .line 379
    .line 380
    move-result-object v6

    .line 381
    invoke-interface {v6, v13}, Ljava/util/List;->get(I)Ljava/lang/Object;

    .line 382
    .line 383
    .line 384
    move-result-object v6

    .line 385
    check-cast v6, LB30/z;

    .line 386
    .line 387
    invoke-direct {v4, v5, v6}, LD30/f$baz;-><init>(ILB30/z;)V

    .line 388
    .line 389
    .line 390
    iput-object v4, v0, LzU/g;->b:Ljava/util/List;

    .line 391
    .line 392
    goto :goto_d

    .line 393
    :cond_17
    invoke-interface {v4}, Ljava/util/List;->clear()V

    .line 394
    .line 395
    .line 396
    :goto_d
    instance-of v5, v4, LD30/f$baz;

    .line 397
    .line 398
    if-eqz v5, :cond_18

    .line 399
    .line 400
    move-object v5, v4

    .line 401
    check-cast v5, LD30/f$baz;

    .line 402
    .line 403
    move-object/from16 v16, v5

    .line 404
    .line 405
    goto :goto_e

    .line 406
    :cond_18
    move-object/from16 v16, v14

    .line 407
    .line 408
    :goto_e
    cmp-long v5, v11, v2

    .line 409
    .line 410
    if-gez v5, :cond_1c

    .line 411
    .line 412
    :goto_f
    cmp-long v5, v2, v11

    .line 413
    .line 414
    if-eqz v5, :cond_1b

    .line 415
    .line 416
    if-eqz v16, :cond_19

    .line 417
    .line 418
    invoke-virtual/range {v16 .. v16}, LD30/f$baz;->peek()Ljava/lang/Object;

    .line 419
    .line 420
    .line 421
    move-result-object v5

    .line 422
    check-cast v5, Ljava/lang/CharSequence;

    .line 423
    .line 424
    goto :goto_10

    .line 425
    :cond_19
    move-object v5, v14

    .line 426
    :goto_10
    instance-of v6, v5, LJ30/F;

    .line 427
    .line 428
    if-eqz v6, :cond_1a

    .line 429
    .line 430
    check-cast v5, LJ30/F;

    .line 431
    .line 432
    move-wide/from16 v17, v2

    .line 433
    .line 434
    move-object v3, v4

    .line 435
    move-object v2, v5

    .line 436
    move-wide/from16 v4, v17

    .line 437
    .line 438
    :goto_11
    const-wide/16 v6, 0x1

    .line 439
    .line 440
    goto :goto_12

    .line 441
    :cond_1a
    move-wide v6, v2

    .line 442
    move-object v3, v4

    .line 443
    move-wide v4, v6

    .line 444
    move-object v2, v14

    .line 445
    goto :goto_11

    .line 446
    :goto_12
    invoke-static/range {v1 .. v7}, LzU/f;->a(LE30/d0;LJ30/F;Ljava/util/List;JJ)J

    .line 447
    .line 448
    .line 449
    move-result-wide v4

    .line 450
    move-wide/from16 v17, v4

    .line 451
    .line 452
    move-object v4, v3

    .line 453
    move-wide/from16 v2, v17

    .line 454
    .line 455
    goto :goto_f

    .line 456
    :cond_1b
    move-object v3, v4

    .line 457
    const-wide/16 v6, 0x1

    .line 458
    .line 459
    invoke-virtual {v1}, LE30/e0;->a()J

    .line 460
    .line 461
    .line 462
    move-result-wide v4

    .line 463
    move-wide/from16 v17, v4

    .line 464
    .line 465
    move-object v4, v3

    .line 466
    move-wide/from16 v2, v17

    .line 467
    .line 468
    goto :goto_e

    .line 469
    :cond_1c
    const-wide/16 v6, 0x1

    .line 470
    .line 471
    goto :goto_14

    .line 472
    :cond_1d
    invoke-virtual {v1}, LE30/d0;->j()I

    .line 473
    .line 474
    .line 475
    move-result v2

    .line 476
    if-eq v2, v13, :cond_1e

    .line 477
    .line 478
    invoke-virtual {v1}, LE30/e0;->n()V

    .line 479
    .line 480
    .line 481
    iput-object v14, v0, LzU/g;->a:Ljava/lang/CharSequence;

    .line 482
    .line 483
    goto :goto_14

    .line 484
    :cond_1e
    iget-object v2, v0, LzU/g;->a:Ljava/lang/CharSequence;

    .line 485
    .line 486
    instance-of v3, v2, LJ30/F;

    .line 487
    .line 488
    if-eqz v3, :cond_1f

    .line 489
    .line 490
    check-cast v2, LJ30/F;

    .line 491
    .line 492
    goto :goto_13

    .line 493
    :cond_1f
    move-object v2, v14

    .line 494
    :goto_13
    invoke-virtual {v1, v2}, LE30/d0;->o(LJ30/F;)LJ30/F;

    .line 495
    .line 496
    .line 497
    move-result-object v2

    .line 498
    iput-object v2, v0, LzU/g;->a:Ljava/lang/CharSequence;

    .line 499
    .line 500
    :goto_14
    add-int/lit8 v15, v15, 0x1

    .line 501
    .line 502
    goto/16 :goto_b

    .line 503
    .line 504
    :cond_20
    return-void
    .line 505
    .line 506
    .line 507
    .line 508
    .line 509
    .line 510
    .line 511
    .line 512
    .line 513
    .line 514
    .line 515
    .line 516
    .line 517
    .line 518
    .line 519
    .line 520
    .line 521
    .line 522
    .line 523
    .line 524
    .line 525
    .line 526
    .line 527
    .line 528
    .line 529
    .line 530
    .line 531
    .line 532
    .line 533
    .line 534
    .line 535
    .line 536
    .line 537
    .line 538
    .line 539
    .line 540
    .line 541
    .line 542
    .line 543
    .line 544
    .line 545
    .line 546
    .line 547
    .line 548
    .line 549
    .line 550
    .line 551
    .line 552
    .line 553
    .line 554
    .line 555
    .line 556
    .line 557
    .line 558
    .line 559
    .line 560
    .line 561
    .line 562
    .line 563
    .line 564
    .line 565
    .line 566
    .line 567
    .line 568
    .line 569
    .line 570
    .line 571
    .line 572
    .line 573
    .line 574
    .line 575
    .line 576
    .line 577
    .line 578
    .line 579
    .line 580
    .line 581
    .line 582
    .line 583
    .line 584
    .line 585
    .line 586
    .line 587
    .line 588
    .line 589
    .line 590
    .line 591
    .line 592
    .line 593
    .line 594
    .line 595
    .line 596
    .line 597
    .line 598
    .line 599
    .line 600
    .line 601
    .line 602
    .line 603
    .line 604
    .line 605
    .line 606
    .line 607
    .line 608
    .line 609
    .line 610
    .line 611
    .line 612
    .line 613
    .line 614
    .line 615
    .line 616
    .line 617
    .line 618
    .line 619
    .line 620
    .line 621
    .line 622
    .line 623
    .line 624
    .line 625
    .line 626
    .line 627
    .line 628
    .line 629
    .line 630
    .line 631
    .line 632
    .line 633
    .line 634
    .line 635
    .line 636
    .line 637
    .line 638
    .line 639
    .line 640
    .line 641
    .line 642
    .line 643
    .line 644
    .line 645
.end method

.method public final get(I)Ljava/lang/Object;
    .locals 2

    .line 1
    if-eqz p1, :cond_4

    .line 2
    .line 3
    const/4 v0, 0x1

    .line 4
    if-eq p1, v0, :cond_3

    .line 5
    .line 6
    const/4 v0, 0x2

    .line 7
    if-eq p1, v0, :cond_2

    .line 8
    .line 9
    const/4 v0, 0x3

    .line 10
    if-eq p1, v0, :cond_1

    .line 11
    .line 12
    const/4 v0, 0x4

    .line 13
    if-ne p1, v0, :cond_0

    .line 14
    .line 15
    iget-object p1, p0, LzU/g;->e:Ljava/lang/CharSequence;

    .line 16
    .line 17
    return-object p1

    .line 18
    :cond_0
    new-instance v0, Ljava/lang/IndexOutOfBoundsException;

    .line 19
    .line 20
    const-string v1, "Invalid index: "

    .line 21
    .line 22
    invoke-static {p1, v1}, Ld;->a(ILjava/lang/String;)Ljava/lang/String;

    .line 23
    .line 24
    .line 25
    move-result-object p1

    .line 26
    invoke-direct {v0, p1}, Ljava/lang/IndexOutOfBoundsException;-><init>(Ljava/lang/String;)V

    .line 27
    .line 28
    .line 29
    throw v0

    .line 30
    :cond_1
    iget-object p1, p0, LzU/g;->d:Ljava/lang/Integer;

    .line 31
    .line 32
    return-object p1

    .line 33
    :cond_2
    iget-object p1, p0, LzU/g;->c:Ljava/lang/Boolean;

    .line 34
    .line 35
    return-object p1

    .line 36
    :cond_3
    iget-object p1, p0, LzU/g;->b:Ljava/util/List;

    .line 37
    .line 38
    return-object p1

    .line 39
    :cond_4
    iget-object p1, p0, LzU/g;->a:Ljava/lang/CharSequence;

    .line 40
    .line 41
    return-object p1
    .line 42
    .line 43
    .line 44
    .line 45
    .line 46
    .line 47
    .line 48
    .line 49
    .line 50
    .line 51
    .line 52
    .line 53
    .line 54
    .line 55
    .line 56
    .line 57
    .line 58
    .line 59
    .line 60
    .line 61
    .line 62
    .line 63
    .line 64
    .line 65
    .line 66
    .line 67
    .line 68
    .line 69
    .line 70
    .line 71
    .line 72
    .line 73
    .line 74
    .line 75
    .line 76
    .line 77
    .line 78
    .line 79
    .line 80
    .line 81
    .line 82
    .line 83
    .line 84
    .line 85
    .line 86
    .line 87
    .line 88
.end method

.method public final getSchema()LB30/z;
    .locals 1

    .line 1
    sget-object v0, LzU/g;->f:LB30/z;

    .line 2
    .line 3
    return-object v0
    .line 4
    .line 5
    .line 6
    .line 7
    .line 8
    .line 9
    .line 10
    .line 11
    .line 12
    .line 13
    .line 14
    .line 15
    .line 16
    .line 17
    .line 18
    .line 19
    .line 20
.end method

.method public final h(LE30/b;)V
    .locals 10
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    .line 1
    iget-object v0, p0, LzU/g;->a:Ljava/lang/CharSequence;

    .line 2
    .line 3
    const/4 v1, 0x1

    .line 4
    const/4 v2, 0x0

    .line 5
    if-nez v0, :cond_0

    .line 6
    .line 7
    invoke-virtual {p1, v2}, LE30/b;->k(I)V

    .line 8
    .line 9
    .line 10
    goto :goto_0

    .line 11
    :cond_0
    invoke-virtual {p1, v1}, LE30/b;->k(I)V

    .line 12
    .line 13
    .line 14
    iget-object v0, p0, LzU/g;->a:Ljava/lang/CharSequence;

    .line 15
    .line 16
    invoke-virtual {p1, v0}, LE30/b;->m(Ljava/lang/CharSequence;)V

    .line 17
    .line 18
    .line 19
    :goto_0
    iget-object v0, p0, LzU/g;->b:Ljava/util/List;

    .line 20
    .line 21
    if-nez v0, :cond_1

    .line 22
    .line 23
    invoke-virtual {p1, v2}, LE30/b;->k(I)V

    .line 24
    .line 25
    .line 26
    goto :goto_2

    .line 27
    :cond_1
    invoke-virtual {p1, v1}, LE30/b;->k(I)V

    .line 28
    .line 29
    .line 30
    iget-object v0, p0, LzU/g;->b:Ljava/util/List;

    .line 31
    .line 32
    invoke-interface {v0}, Ljava/util/List;->size()I

    .line 33
    .line 34
    .line 35
    move-result v0

    .line 36
    int-to-long v3, v0

    .line 37
    invoke-virtual {p1, v3, v4}, LE30/b;->b(J)V

    .line 38
    .line 39
    .line 40
    iget-object v0, p0, LzU/g;->b:Ljava/util/List;

    .line 41
    .line 42
    invoke-interface {v0}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    .line 43
    .line 44
    .line 45
    move-result-object v0

    .line 46
    const-wide/16 v5, 0x0

    .line 47
    .line 48
    :goto_1
    invoke-interface {v0}, Ljava/util/Iterator;->hasNext()Z

    .line 49
    .line 50
    .line 51
    move-result v7

    .line 52
    if-eqz v7, :cond_2

    .line 53
    .line 54
    invoke-interface {v0}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    .line 55
    .line 56
    .line 57
    move-result-object v7

    .line 58
    check-cast v7, Ljava/lang/CharSequence;

    .line 59
    .line 60
    const-wide/16 v8, 0x1

    .line 61
    .line 62
    add-long/2addr v5, v8

    .line 63
    invoke-virtual {p1, v7}, LE30/b;->m(Ljava/lang/CharSequence;)V

    .line 64
    .line 65
    .line 66
    goto :goto_1

    .line 67
    :cond_2
    invoke-virtual {p1}, LE30/b;->o()V

    .line 68
    .line 69
    .line 70
    cmp-long v0, v5, v3

    .line 71
    .line 72
    if-nez v0, :cond_6

    .line 73
    .line 74
    :goto_2
    iget-object v0, p0, LzU/g;->c:Ljava/lang/Boolean;

    .line 75
    .line 76
    if-nez v0, :cond_3

    .line 77
    .line 78
    invoke-virtual {p1, v2}, LE30/b;->k(I)V

    .line 79
    .line 80
    .line 81
    goto :goto_3

    .line 82
    :cond_3
    invoke-virtual {p1, v1}, LE30/b;->k(I)V

    .line 83
    .line 84
    .line 85
    iget-object v0, p0, LzU/g;->c:Ljava/lang/Boolean;

    .line 86
    .line 87
    invoke-virtual {v0}, Ljava/lang/Boolean;->booleanValue()Z

    .line 88
    .line 89
    .line 90
    move-result v0

    .line 91
    invoke-virtual {p1, v0}, LE30/b;->c(Z)V

    .line 92
    .line 93
    .line 94
    :goto_3
    iget-object v0, p0, LzU/g;->d:Ljava/lang/Integer;

    .line 95
    .line 96
    if-nez v0, :cond_4

    .line 97
    .line 98
    invoke-virtual {p1, v2}, LE30/b;->k(I)V

    .line 99
    .line 100
    .line 101
    goto :goto_4

    .line 102
    :cond_4
    invoke-virtual {p1, v1}, LE30/b;->k(I)V

    .line 103
    .line 104
    .line 105
    iget-object v0, p0, LzU/g;->d:Ljava/lang/Integer;

    .line 106
    .line 107
    invoke-virtual {v0}, Ljava/lang/Integer;->intValue()I

    .line 108
    .line 109
    .line 110
    move-result v0

    .line 111
    invoke-virtual {p1, v0}, LE30/b;->k(I)V

    .line 112
    .line 113
    .line 114
    :goto_4
    iget-object v0, p0, LzU/g;->e:Ljava/lang/CharSequence;

    .line 115
    .line 116
    if-nez v0, :cond_5

    .line 117
    .line 118
    invoke-virtual {p1, v2}, LE30/b;->k(I)V

    .line 119
    .line 120
    .line 121
    return-void

    .line 122
    :cond_5
    invoke-virtual {p1, v1}, LE30/b;->k(I)V

    .line 123
    .line 124
    .line 125
    iget-object v0, p0, LzU/g;->e:Ljava/lang/CharSequence;

    .line 126
    .line 127
    invoke-virtual {p1, v0}, LE30/b;->m(Ljava/lang/CharSequence;)V

    .line 128
    .line 129
    .line 130
    return-void

    .line 131
    :cond_6
    new-instance p1, Ljava/util/ConcurrentModificationException;

    .line 132
    .line 133
    const-string v0, "Array-size written was "

    .line 134
    .line 135
    const-string v1, ", but element count was "

    .line 136
    .line 137
    invoke-static {v3, v4, v0, v1}, LD0/z;->b(JLjava/lang/String;Ljava/lang/String;)Ljava/lang/StringBuilder;

    .line 138
    .line 139
    .line 140
    move-result-object v0

    .line 141
    const-string v1, "."

    .line 142
    .line 143
    invoke-static {v5, v6, v1, v0}, LIo/U;->b(JLjava/lang/String;Ljava/lang/StringBuilder;)Ljava/lang/String;

    .line 144
    .line 145
    .line 146
    move-result-object v0

    .line 147
    invoke-direct {p1, v0}, Ljava/util/ConcurrentModificationException;-><init>(Ljava/lang/String;)V

    .line 148
    .line 149
    .line 150
    throw p1
    .line 151
    .line 152
    .line 153
    .line 154
    .line 155
    .line 156
    .line 157
    .line 158
    .line 159
    .line 160
    .line 161
    .line 162
    .line 163
    .line 164
    .line 165
    .line 166
    .line 167
    .line 168
    .line 169
    .line 170
    .line 171
    .line 172
    .line 173
    .line 174
    .line 175
    .line 176
    .line 177
    .line 178
    .line 179
    .line 180
    .line 181
    .line 182
    .line 183
    .line 184
    .line 185
    .line 186
    .line 187
    .line 188
    .line 189
    .line 190
    .line 191
    .line 192
    .line 193
    .line 194
    .line 195
    .line 196
    .line 197
    .line 198
    .line 199
    .line 200
    .line 201
    .line 202
    .line 203
    .line 204
    .line 205
    .line 206
    .line 207
    .line 208
    .line 209
    .line 210
    .line 211
    .line 212
    .line 213
    .line 214
    .line 215
    .line 216
    .line 217
    .line 218
    .line 219
    .line 220
    .line 221
    .line 222
    .line 223
    .line 224
    .line 225
    .line 226
    .line 227
    .line 228
    .line 229
    .line 230
    .line 231
    .line 232
    .line 233
    .line 234
    .line 235
    .line 236
    .line 237
    .line 238
    .line 239
.end method

.method public final i()LI30/g;
    .locals 1

    .line 1
    sget-object v0, LzU/g;->g:LI30/g;

    .line 2
    .line 3
    return-object v0
    .line 4
    .line 5
    .line 6
    .line 7
    .line 8
    .line 9
    .line 10
    .line 11
    .line 12
    .line 13
    .line 14
    .line 15
    .line 16
    .line 17
    .line 18
    .line 19
    .line 20
.end method

.method public final j()Z
    .locals 1

    .line 1
    const/4 v0, 0x1

    .line 2
    return v0
    .line 3
    .line 4
    .line 5
    .line 6
    .line 7
    .line 8
    .line 9
    .line 10
    .line 11
    .line 12
    .line 13
    .line 14
    .line 15
    .line 16
    .line 17
    .line 18
    .line 19
    .line 20
.end method

.method public final readExternal(Ljava/io/ObjectInput;)V
    .locals 1
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    .line 1
    sget-object v0, LzU/g;->i:LI30/h;

    .line 2
    .line 3
    invoke-static {p1}, LI30/g;->w(Ljava/io/ObjectInput;)LE30/g;

    .line 4
    .line 5
    .line 6
    move-result-object p1

    .line 7
    invoke-virtual {v0, p0, p1}, LD30/i;->b(Ljava/lang/Object;LE30/e;)Ljava/lang/Object;

    .line 8
    .line 9
    .line 10
    return-void
    .line 11
    .line 12
    .line 13
    .line 14
    .line 15
    .line 16
    .line 17
    .line 18
    .line 19
    .line 20
    .line 21
    .line 22
    .line 23
    .line 24
    .line 25
    .line 26
    .line 27
    .line 28
.end method

.method public final writeExternal(Ljava/io/ObjectOutput;)V
    .locals 1
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    .line 1
    sget-object v0, LzU/g;->h:LI30/i;

    .line 2
    .line 3
    invoke-static {p1}, LI30/g;->x(Ljava/io/ObjectOutput;)LE30/h;

    .line 4
    .line 5
    .line 6
    move-result-object p1

    .line 7
    invoke-virtual {v0, p0, p1}, LD30/r;->d(Ljava/lang/Object;LE30/b;)V

    .line 8
    .line 9
    .line 10
    return-void
    .line 11
    .line 12
    .line 13
    .line 14
    .line 15
    .line 16
    .line 17
    .line 18
    .line 19
    .line 20
    .line 21
    .line 22
    .line 23
    .line 24
    .line 25
    .line 26
    .line 27
    .line 28
.end method
