package com.fyber.inneractive.sdk.network;

import com.google.android.gms.wallet.WalletConstants;
import com.os.InterfaceC13473h3;
import com.os.mediationsdk.logger.IronSourceError;
import com.truecaller.api.services.messenger.v1.events.Event;
import com.vungle.ads.internal.protos.Sdk$SDKError;
import io.agora.rtc2.Constants;
import io.agora.rtc2.internal.RtcEngineEvent;
import java.util.HashMap;

/* loaded from: classes3.dex */
public enum t {
    VAST_ERROR_DVC_FAILURE(46),
    FMP_SDK_INIT_FAILED(62),
    VAST_COMPANION_FAILED_LOADING(70),
    VAST_COMPANION_INCOMPATIBLE_MIMETYPE(75),
    FMP_COMPANION_FAILED_LOADING(78),
    ERROR_STORE_PROMO_FAILURE(96),
    VAST_ERROR_INVALID_RESPONSE(Sdk$SDKError.baz.MRAID_ERROR_VALUE),
    VAST_ERROR_TOO_MANY_WRAPPERS(Sdk$SDKError.baz.INVALID_IFA_STATUS_VALUE),
    VAST_ERROR_NO_MEDIA_FILES(303),
    VAST_ERROR_NO_COMPATIBLE_MEDIA_FILE(Sdk$SDKError.baz.AD_EXPIRED_VALUE),
    VAST_ERROR_PRE_BUFFER_TIMEOUT(306),
    VAST_ERROR_BUFFER_TIMEOUT(Sdk$SDKError.baz.AD_EXPIRED_ON_PLAY_VALUE),
    VAST_ERROR_FAILED_PLAYING_MEDIA_FILE(Sdk$SDKError.baz.AD_WIN_NOTIFICATION_ERROR_VALUE),
    VAST_ERROR_FAILED_PLAYING_ALL_MEDIA_FILES(Sdk$SDKError.baz.MRAID_JS_CALL_EMPTY_VALUE),
    VAST_ERROR_UNSECURE_URL(Sdk$SDKError.baz.DEEPLINK_OPEN_FAILED_VALUE),
    MRAID_ERROR_UNSECURE_CONTENT(Sdk$SDKError.baz.EVALUATE_JAVASCRIPT_FAILED_VALUE),
    VPAID_ERROR_UNSECURE_CONTENT(Sdk$SDKError.baz.LINK_COMMAND_OPEN_FAILED_VALUE),
    MRAID_VIDEO_HAS_NOT_STARTED_PLAYING_IN_A_TIMELY_FASHION(390),
    VAST_UNKNOWN_PLAYER_ERROR(399),
    NATIVE_ERROR_INVALID_NATIVE_RESPONSE(401),
    NATIVE_ERROR_MISSING_PUB_REQUIRED_FIELD(WalletConstants.ERROR_CODE_SERVICE_UNAVAILABLE),
    NATIVE_ERROR_MISMATCH_REQUIRED_ASSET_RESPONSE(404),
    NATIVE_ERROR_INVALID_REQUIRED_ASSET_DATA(405),
    NATIVE_ERROR_INVALID_OPTIONAL_ASSET_DATA(406),
    NATIVE_ERROR_INVALID_LINK_WEB_URL(InterfaceC13473h3.a.b.f113197g),
    NATIVE_ERROR_FAILED_LOAD_ASSET(410),
    NATIVE_ERROR_MISMATCH_OPTIONAL_ASSET_RESPONSE(411),
    NATIVE_ERROR_MISSING_PROTOCOL_REQUIRED_FIELD(WalletConstants.ERROR_CODE_UNSUPPORTED_API_VERSION),
    NATIVE_ERROR_RECEIVED_VIDEO_BUT_NOT_SUPPORTED(WalletConstants.ERROR_CODE_UNKNOWN),
    NATIVE_ERROR_NO_VALID_URLS_FOR_CLICK(414),
    NATIVE_ERROR_SOME_INVALID_URLS_FOR_PROCESSED_CLICK(415),
    MRAID_AUTO_ACTION_DETECTED(IronSourceError.ERROR_CODE_NO_CONFIGURATION_AVAILABLE),
    INTERNAL_CONFIG_MISMATCH(IronSourceError.ERROR_BN_LOAD_AFTER_LONG_INITIATION),
    FATAL_ADM_PARSING_ERROR(IronSourceError.ERROR_BN_LOAD_WHILE_LONG_INITIATION),
    FATAL_ADM_MARKUP_FETCHING_ERROR(IronSourceError.ERROR_BN_LOAD_PLACEMENT_CAPPED),
    TOKEN_EXCEEDS_LIMIT(IronSourceError.ERROR_BN_LOAD_EXCEPTION),
    IGNITE_FLOW_MODE_NOT_COMPATIBLE(606),
    IGNITE_FLOW_FAILED_TO_START(IronSourceError.ERROR_BN_INSTANCE_INIT_TIMEOUT),
    IGNITE_FLOW_FAILED_TO_INSTALL_APP(IronSourceError.ERROR_BN_INSTANCE_INIT_EXCEPTION),
    IGNITE_FLOW_FAILED_TO_LOAD_WEBPAGE(IronSourceError.ERROR_BN_RELOAD_SKIP_INVISIBLE),
    FATAL_CONFIGURATION_ERROR(701),
    FATAL_FEATURES_CONFIG_ERROR(IronSourceError.ERROR_NT_LOAD_PLACEMENT_CAPPED),
    IA_AD_LOAD_FAILED(Constants.RHYTHM_PLAYER_ERROR_CAN_NOT_OPEN),
    IA_AD_EXPIRED(Constants.RHYTHM_PLAYER_ERROR_CAN_NOT_PLAY),
    IA_AD_DESTROYED_WITHOUT_SHOW(Constants.RHYTHM_PLAYER_ERROR_FILE_OVER_DURATION_LIMIT),
    IA_AD_FAILURE_DATA(850),
    CLICK_PARSING_FAILURE(991),
    MISSMATCH_SPOTID(992),
    FAILED_DNS(Event.BATCH_FIELD_NUMBER),
    FETCH_TOKEN_DV_ERROR(1000),
    DV_ERROR_PHASE(1001),
    ODT_ENCRYPTION_EXCEPTION(1100),
    ODT_RAW_ONE_DT_ERROR(RtcEngineEvent.EvtType.EVT_TRANSPORT_QUALITY),
    ODT_ONE_DT_PARSE_ERROR(RtcEngineEvent.EvtType.EVT_AUDIO_QUALITY),
    ODT_ONE_DT_AUTHENTICATION_ERROR(RtcEngineEvent.EvtType.EVT_TRANSPORT_SERVER_INSTANCE),
    ODT_ONE_DT_BROADCAST_ERROR(RtcEngineEvent.EvtType.EVT_MEDIA_ENGINE_EVENT),
    ODT_ONE_DT_REQUEST_ERROR(RtcEngineEvent.EvtType.EVT_AUDIO_DEVICE_STATE_CHANGED),
    ODT_ONE_DT_GENERAL_ERROR(RtcEngineEvent.EvtType.EVT_API_CALL_EXECUTED);

    private static final HashMap<Integer, t> sMap = new HashMap<>();
    int val;

    static {
        for (t tVar : values()) {
            sMap.put(Integer.valueOf(tVar.val), tVar);
        }
    }

    t(int i11) {
        this.val = i11;
    }

    public static t a(D7.a aVar) {
        return sMap.get(Integer.valueOf(aVar.f12778a));
    }
}
