package com.google.android.gms.internal.mlkit_common;

import com.google.ads.mediation.facebook.FacebookMediationAdapter;
import com.google.android.gms.wallet.WalletConstants;
import com.os.InterfaceC13473h3;
import com.os.mediationsdk.logger.IronSourceError;
import com.vungle.ads.internal.protos.Sdk$SDKError;

/* loaded from: classes4.dex */
public enum zzmu implements zzba {
    NO_ERROR(0),
    INCOMPATIBLE_INPUT(1),
    INCOMPATIBLE_OUTPUT(2),
    INCOMPATIBLE_TFLITE_VERSION(3),
    MISSING_OP(4),
    DATA_TYPE_ERROR(6),
    TFLITE_INTERNAL_ERROR(7),
    TFLITE_UNKNOWN_ERROR(8),
    MEDIAPIPE_ERROR(9),
    TIME_OUT_FETCHING_MODEL_METADATA(5),
    MODEL_NOT_DOWNLOADED(100),
    URI_EXPIRED(101),
    NO_NETWORK_CONNECTION(102),
    METERED_NETWORK(103),
    DOWNLOAD_FAILED(104),
    MODEL_INFO_DOWNLOAD_UNSUCCESSFUL_HTTP_STATUS(105),
    MODEL_INFO_DOWNLOAD_NO_HASH(106),
    MODEL_INFO_DOWNLOAD_CONNECTION_FAILED(107),
    NO_VALID_MODEL(FacebookMediationAdapter.ERROR_MAPPING_NATIVE_ASSETS),
    LOCAL_MODEL_INVALID(109),
    REMOTE_MODEL_INVALID(110),
    REMOTE_MODEL_LOADER_ERROR(111),
    REMOTE_MODEL_LOADER_LOADS_NO_MODEL(112),
    SMART_REPLY_LANG_ID_DETECTAION_FAILURE(113),
    MODEL_NOT_REGISTERED(114),
    MODEL_TYPE_MISUSE(115),
    MODEL_HASH_MISMATCH(116),
    OPTIONAL_MODULE_NOT_AVAILABLE(201),
    OPTIONAL_MODULE_INIT_ERROR(202),
    OPTIONAL_MODULE_INFERENCE_ERROR(203),
    OPTIONAL_MODULE_RELEASE_ERROR(204),
    OPTIONAL_TFLITE_MODULE_INIT_ERROR(205),
    NATIVE_LIBRARY_LOAD_ERROR(206),
    OPTIONAL_MODULE_CREATE_ERROR(207),
    CAMERAX_SOURCE_ERROR(Sdk$SDKError.baz.MRAID_ERROR_VALUE),
    CAMERA1_SOURCE_CANT_START_ERROR(Sdk$SDKError.baz.INVALID_IFA_STATUS_VALUE),
    CAMERA1_SOURCE_NO_SUITABLE_SIZE_ERROR(303),
    CAMERA1_SOURCE_NO_SUITABLE_FPS_ERROR(Sdk$SDKError.baz.AD_EXPIRED_VALUE),
    CAMERA1_SOURCE_NO_BYTE_SOURCE_FOUND_ERROR(Sdk$SDKError.baz.MRAID_BRIDGE_ERROR_VALUE),
    CODE_SCANNER_UNAVAILABLE(400),
    CODE_SCANNER_CANCELLED(401),
    CODE_SCANNER_CAMERA_PERMISSION_NOT_GRANTED(WalletConstants.ERROR_CODE_SERVICE_UNAVAILABLE),
    CODE_SCANNER_APP_NAME_UNAVAILABLE(403),
    CODE_SCANNER_TASK_IN_PROGRESS(404),
    CODE_SCANNER_PIPELINE_INITIALIZATION_ERROR(405),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(406),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(InterfaceC13473h3.a.b.f113197g),
    LOW_LIGHT_AUTO_EXPOSURE_COMPUTATION_FAILURE(500),
    LOW_LIGHT_IMAGE_CAPTURE_PROCESSING_FAILURE(IronSourceError.ERROR_CODE_NO_CONFIGURATION_AVAILABLE),
    PERMISSION_DENIED(600),
    CANCELLED(IronSourceError.ERROR_BN_LOAD_AFTER_LONG_INITIATION),
    GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(IronSourceError.ERROR_BN_INIT_FAILED_AFTER_LOAD),
    LOW_MEMORY(IronSourceError.ERROR_BN_LOAD_WHILE_LONG_INITIATION),
    UNKNOWN_ERROR(9999);

    private final int zzad;

    zzmu(int i11) {
        this.zzad = i11;
    }

    @Override // com.google.android.gms.internal.mlkit_common.zzba
    public final int zza() {
        return this.zzad;
    }
}
